### ISSUE TITLE
The specific key should not have the default value

### ISSUE THREAD

**Issue by peter279k** [Lablnet/PHP-Encryption#1]
As title, it seems that the `Encryption::__construct` has the `$key` argument and it has the default key value.

I think it's not required because this key is up to the users to specify their key.

The `$key` always should be the required argument.

We don't have to set the default key because this will cause security problem.

Once someone know the default key from this repo, they will try to do some crack work.

**Comment by lablnet** [comment]
@peter279k  thanks you so much, appreciated.
